### ISSUE TITLE
Deploy module Main bị lỗi

### ISSUE THREAD

**Issue by lekien-2803** [lekien-2803/techmt-practice#1]
## 1. Mục tiêu
Deploy thành công module main.

## 2. Thực hành
Làm theo hướng dẫn tại module [02-main](https://github.com/lekien-2803/techmt-practice/tree/main/02-main) với file `docker-compose.yml` như sau:

```yaml
version: '3'

volumes:
  db_tech:
  redis_data:

networks:
  techmaster_backend:
    external: true


services:
  redis:
      image: redis
      command: redis-server --requirepass 123
      ports:
        - "6379:6379"
      volumes:
        - redis_data:/data
      networks:
      - techmaster_backend

  mainsite:
    image: 192.168.56.101:5000/main-site
    ports: 
     - "8079:8079"
    depends_on:
     - postgres
     - redis
    networks:
      - techmaster_backend

  postgres:
    image: 192.168.56.101:5000/postgres-tech
    volumes:
      - db_tech:/var/lib/postgresql/data
    ports:
      - 5433:5432
    environment:
      POSTGRES_PASSWORD: 123      
    networks:
      - techmaster_backend
```

## 3. Lỗi

Service của main-site không chạy ở bất cứ node nào trong swarm:

![image](https://github.com/lekien-2803/techmt-practice/assets/144997507/3c63ab55-37dc-4a35-ac80-8f120a937134)

### 3.1 Thiếu file `config.product`
Vào đọc logs thì thông báo:

![image](https://github.com/lekien-2803/techmt-practice/assets/144997507/185578ae-38a6-4676-a046-774db2240e11)

#### Giải quyết
Ban đầu thì cũng chẳng hiểu cái file config này sẽ nằm ở thư mục nào, tuy nhiên để ý kĩ sẽ thấy đường dẫn tới thư viện `core` của Techmaster.

Mò vào được thư viện `core` và thấy được cái file `config.product.json` tại [đây](https://github.com/TechMaster/core/tree/main):

![image](https://github.com/lekien-2803/techmt-practice/assets/144997507/177adcf7-60dc-4fd7-bb8c-711eea5e1658)

Kéo readme xuống đọc thì thấy lưu ý:

![image](https://github.com/lekien-2803/techmt-practice/assets/144997507/5f9a3936-c518-426e-909b-82369d76fde4)

Tuy nhiên trong cái repo Đức đưa thì chỉ có một file `config`:

![image](https://github.com/lekien-2803/techmt-practice/assets/144997507/a49b613b-f5c7-47f6-a009-8af9d54d15c8)

Giờ copy file `config.produc.json` này vào thư mục gốc:

```yaml
{
    "port": ":8079",
    "host": "localhost:8079",
    "allowed_origins": ["*"],
    "database": {
      "user": "postgres",
      "password": "123",
      "database": "demo",
      "address": "localhost:5432"
    },
    "redis": {
      "network": "tcp",
      "addr": "redis:6379",
      "password": "",
      "database": "",
      "max_idle": 0,
      "max_active": 0,
      "idle_timeout": 5,
      "prefix": ""
    },
    "authenticate": {
      "max_access_failed": 5,
      "lockout_in_minutes": 10,
      "black_list_token_in_days": -10
    }
  }
  ```
Tiếp theo ta để ý logs báo rằng file này cần được chạy trên thư mục `/run/secret`, nghĩa là file này sẽ được mount vào đường dẫn `/run/secret` trong container. 

Vậy thì ta sẽ tạo một secret với file này:

```bash
docker secret create config-product config.product.json
```

Sau đó thêm vào file `docker-compose.yml` cấu hình secret cho service `mainsite`:
```yaml
version: '3'
   # các cấu hình khác
   
# khai báo sử dụng secret bên ngoài là config-product
secrets:
  config-product:
    external: true    

  mainsite:
    # các thuộc tính khác
    # khai báo thêm thuộc tính secrets
    secrets:
      - source: config_product
        target: /run/secrets/config.product

 #các cấu hình khác
```

### 3.2. Lỗi "NOAUTH Authentication required"

![image](https://github.com/lekien-2803/techmt-practice/assets/144997507/e4029ff9-3a50-4ef2-bcc4-859b979334e3)

#### Giải quyết

Thêm mật khẩu trong file cấu hình `config.product.json`:
```json
    "redis": {
     // các cấu hình khác
      "password": "123",
    },
```
